### ISSUE TITLE
EPIC: Tutor Assignments

### ISSUE THREAD

**Issue by scottpchow23** [ucsb-cs56-f19/ucsb-tutor-scheduler#11]
- [ ] Download Tutor Assignments as a CSV
- [ ] Make list of Tutor Assignments sorted by quarter, then course, then role, then name.
- [ ] Filter the list of Tutor Assignments by Quarter, only displaying results with that quarter.
