### ISSUE TITLE
EPIC: Course Offerings

### ISSUE THREAD

**Issue by scottpchow23** [ucsb-cs56-f19/ucsb-tutor-scheduler#12]
- [x] Move the list of tutor assignments to the course page.
- [x] Don't allow duplicate assignments of tutors to a course offering.
- [x] Don't allow assignments of a tutor to multiple course offerings with the same quarter.
