### ISSUE TITLE
EPIC: Rooms and TimeSlots

### ISSUE THREAD

**Issue by scottpchow23** [ucsb-cs56-f19/ucsb-tutor-scheduler#13]
- [ ] Add the relationship that a Room has many TimeSlots
- [x] Add the quarter field to a TimeSlot
- [ ] Add the relationship that a TimeSlot has many TutorAssignments
- [ ] *Bonus:* Display the schedule for a given Room on the Room's show page
